package edu.gduf.liu.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private Integer id;
	private String opId;
	private Date optime;
	private String logInfo;

	public Log() {
	}

	public Log(String opId, Date optime, String logInfo) {
		this.opId = opId;
		this.optime = optime;
		this.logInfo = logInfo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOpId() {
		return this.opId;
	}

	public void setOpId(String opId) {
		this.opId = opId;
	}

	public Date getOptime() {
		return this.optime;
	}

	public void setOptime(Date optime) {
		this.optime = optime;
	}

	public String getLogInfo() {
		return this.logInfo;
	}

	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo;
	}

}
