package edu.gduf.liu.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String stuNum;
	private String stuName;
	private String sex;
	private String major;
	private String dept;
	private String mobilephone;
	private String email;

	public Student() {
	}

	public Student(String stuNum, String stuName) {
		this.stuNum = stuNum;
		this.stuName = stuName;
	}

	public Student(String stuNum, String stuName, String sex, String major,
			String dept, String mobilephone, String email) {
		this.stuNum = stuNum;
		this.stuName = stuName;
		this.sex = sex;
		this.major = major;
		this.dept = dept;
		this.mobilephone = mobilephone;
		this.email = email;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
