package com.kevin.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Annex generated by hbm2java
 */
public class Annex implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date uploadTime;
	private String annexDesc;
	private int downloads;
	private String path;
	private String owner;
	private int share;

	public Annex() {
	}

	public Annex(String name, Date uploadTime, int downloads, String path,
			String owner, int share) {
		this.name = name;
		this.uploadTime = uploadTime;
		this.downloads = downloads;
		this.path = path;
		this.owner = owner;
		this.share = share;
	}

	public Annex(String name, Date uploadTime, String annexDesc, int downloads,
			String path, String owner, int share) {
		this.name = name;
		this.uploadTime = uploadTime;
		this.annexDesc = annexDesc;
		this.downloads = downloads;
		this.path = path;
		this.owner = owner;
		this.share = share;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getAnnexDesc() {
		return this.annexDesc;
	}

	public void setAnnexDesc(String annexDesc) {
		this.annexDesc = annexDesc;
	}

	public int getDownloads() {
		return this.downloads;
	}

	public void setDownloads(int downloads) {
		this.downloads = downloads;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public int getShare() {
		return this.share;
	}

	public void setShare(int share) {
		this.share = share;
	}

}
