package com.kevin.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

/**
 * Config generated by hbm2java
 */
public class Config implements java.io.Serializable {

	private Integer id;
	private String name;
	private String value;

	public Config() {
	}

	public Config(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
