package com.kevin.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private int id;
	private String title;
	private String publisher;
	private Date releaseTime;
	private Date validityDate;

	public Notice() {
	}

	public Notice(int id, String title, String publisher, Date releaseTime,
			Date validityDate) {
		this.id = id;
		this.title = title;
		this.publisher = publisher;
		this.releaseTime = releaseTime;
		this.validityDate = validityDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getReleaseTime() {
		return this.releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	public Date getValidityDate() {
		return this.validityDate;
	}

	public void setValidityDate(Date validityDate) {
		this.validityDate = validityDate;
	}

}
