package com.kevin.entity2;

// Generated 2013-8-9 0:38:56 by Hibernate Tools 4.0.0

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

	private Integer id;
	private float score;
	private int courseId;
	private String stuNum;

	public Score() {
	}

	public Score(float score, int courseId, String stuNum) {
		this.score = score;
		this.courseId = courseId;
		this.stuNum = stuNum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public float getScore() {
		return this.score;
	}

	public void setScore(float score) {
		this.score = score;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}

}
